maxwelbm/alkemy-g7

internal/handler/product.go
internal/model/products.go
internal/repository/interfaces/iproducts.go
internal/repository/products.go
internal/service/interfaces/iproducts.go
internal/service/products.go

Criado o ProductHandler: Adicionada a estrutura ProductHandler com métodos para obter todos os produtos. Este manipulador interage com a camada de serviço para recuperar informações e formatar a resposta JSON.
Definido o modelo de produtos: Incluídos os structs Product e Products, que representam a estrutura dos dados dos produtos, incluindo atributos como ID, ProductCode, Description, dimensões e taxas relevantes.
Interface IProductsRepo: Implementada uma interface que define os métodos necessários para manipulação de produtos, como GetAll, GetById, Post, Update e Delete.
Implementação do ProductRepository: Criado o repositório de produtos com acesso à camada de dados. Implementados métodos para obter todos os produtos e buscar um produto específico por ID, com tratamento de erros para …

[RQ.4 - GET] Implementação das funcionalidades básicas para gerenciamento de produtos

---

cmd/database/dependencies/dependencies.go
cmd/database/docs/products.json
internal/handler/product.go
internal/service/products.go

Adicionada a lógica no serviço de produtos para buscar um produto específico pelo seu ID. Isso permite uma recuperação mais detalhada e específica das informações do produto.
Criado um novo método no ProductHandler que permite manipular requisições para obter um produto por ID. O manipulador retornará os detalhes do produto solicitado ou mensagens de erro apropriadas, caso o produto não seja encontrado.

Implementação da lógica para busca de produto por ID

---

cmd/dependencies/dependencies.go
cmd/main.go
internal/handler/warehouse.go
internal/model/warehouse.go
internal/repository/interfaces/iwarehouse.go
internal/repository/warehouse.go
internal/service/interfaces/iwarehouse.go
internal/service/warehouse.go
pkg/database/config.go
pkg/database/docs/warehouse.json

Quando a solicitação for bem-sucedida, o backend retornará as informações solicitadas sobre o depósito.
Quando o Warehouse não existir, um código 404 será retornado.

[REQ2] GETBYID-WAREHOUSE

---

cmd/main.go
go.mod
internal/handler/warehouse.go
internal/repository/interfaces/iwarehouse.go
internal/repository/warehouse.go
internal/service/interfaces/iwarehouse.go
internal/service/warehouse.go

Um código 204 será retornado quando a exclusão for bem-sucedida.
Quando o depósito não existir, será retornado um código 404.

[REQ2] DELETE-ID-WAREHOUSE

---

cmd/main.go
internal/handler/request/request.go
internal/handler/warehouse.go
internal/repository/interfaces/iwarehouse.go
internal/repository/warehouse.go
internal/service/interfaces/iwarehouse.go
internal/service/warehouse.go
pkg/custom_error/custom_error.go

Quando a entrada de dados for bem-sucedida, um código 201 será retornado junto com o objeto inserido.
Se o objeto JSON não contiver os campos obrigatórios, será retornado um código 422.

[REQ2] POST WAREHOUSE

---

internal/handler/seller.go
internal/repository/interfaces/iseller.go
internal/repository/seller.go
internal/service/interfaces/iseller.go
internal/service/seller.go

RQ1 - POST CREATE SELLERS

---

internal/handler/responses/response.go
internal/handler/section.go
internal/repository/sections.go

Criada a rota para GET BY ID das sections e a lógica no handler e repository.

RQ3 - GET BY ID SECTIONS 

---

internal/handler/responses/response.go
internal/handler/section.go
internal/repository/sections.go

Implementado a lógica para deleção de uma _Section_. Um código 204 será retornado quando a exclusão for bem-sucedida. Quando a seção não existir, será retornado um código 404.

RQ3 - DELETE SECTIONS

---

internal/handler/section.go
internal/repository/sections.go
internal/service/sections.go
pkg/database/docs/sections.json

Implementado a lógica para atualizar as _Sections_. Quando a atualização de dados for bem-sucedida, a seção será retornada com as informações atualizadas juntamente com um código 200 (você pode atualizar quantos campos quiser). Se a seção a ser atualizada não existir, será retornado um código 404.

REQ 3 - PATCH SECTIONS

---

internal/handler/seller.go
internal/model/seller.go
internal/repository/interfaces/iseller.go
internal/repository/seller.go
internal/service/interfaces/iseller.go
internal/service/seller.go

#43 RQ1 - PATCH - UPDATE SELLERS

RQ1 - PATCH - UPDATE SELLERS

---

cmd/main.go
internal/handler/warehouse.go
internal/repository/interfaces/iwarehouse.go
internal/repository/warehouse.go
internal/service/interfaces/iwarehouse.go
internal/service/warehouse.go

Quando a atualização de dados for bem-sucedida, o depósito será retornado com as informações atualizadas juntamente com um código 200 (você pode atualizar quantos campos quiser).
Se o tipo de armazém a ser atualizado não existir, será retornado um código 404.

[REQ2] UPDATE WAREHOUSE

---

internal/handler/seller.go
internal/model/seller.go
internal/repository/interfaces/iseller.go
internal/repository/seller.go
internal/service/interfaces/iseller.go
internal/service/seller.go

RQ1 - DELETE SELLERS

---

internal/handler/seller.go
internal/model/seller.go
internal/service/seller.go

Fix: implemented logic for empty body in patch request

---

cmd/dependencies/dependencies.go
internal/handler/section.go
internal/model/section.go
internal/repository/sections.go
internal/service/sections.go
pkg/database/docs/sections.json

#76 RQ3 GET ALL SECTIONS USING MYSQL

RQ3 - GET ALL SECTIONS MYSQL

---

cmd/dependencies/dependencies.go
internal/handler/section.go
internal/model/section.go
internal/repository/interfaces/isection.go
internal/repository/sections.go
internal/service/interfaces/isection.go
internal/service/sections.go
pkg/custom_error/custom_error.go
pkg/database/docs/sections.json

#95 RQ3 UPDATE SECTIONS USING MYSQL

RQ3 - UPDATE SECTIONS MYSQL

---

cmd/dependencies/dependencies.go
internal/handler/section.go
internal/model/section.go
internal/repository/interfaces/isection.go
internal/repository/sections.go
internal/service/interfaces/isection.go
internal/service/sections.go
pkg/custom_error/custom_error.go
pkg/database/docs/sections.json

#97 RQ3 DELETE SECTIONS USING MYSQL

RQ3 - DELETE SECTIONS MYSQL

---

internal/handler/seller.go
internal/model/seller.go
internal/repository/interfaces/iseller.go
internal/repository/seller.go
internal/service/interfaces/iseller.go
internal/service/seller.go

MySQL database implemented with query statements used with the necessary methods for requests, as well as the implementation of API response standardization in conjunction with other entities.
#85

RQ1-SELLERS-REPOSITORY-WITH-MYSQL

---

internal/handler/locality.go
internal/handler/seller.go
internal/model/locality.go
internal/model/seller.go
internal/repository/interfaces/ilocality.go
internal/repository/interfaces/iseller.go
internal/repository/locality.go
internal/repository/seller.go
internal/service/interfaces/ilocality.go
internal/service/interfaces/iseller.go
internal/service/locality.go
internal/service/seller.go

RQ1-LOCALITIES-CREATE AND GETBYID

---

internal/handler/product_batches.go
internal/model/product_batches.go
internal/repository/interfaces/iproduct_batches.go
internal/repository/product_batches.go
internal/service/interfaces/iproduct_batches.go
internal/service/product_batches.go

RQ3 - POST PRODUCT BATCHES

---

internal/handler/locality.go
internal/handler/seller.go
internal/model/locality.go
internal/model/seller.go
internal/repository/interfaces/ilocality.go
internal/repository/locality.go
internal/repository/seller.go
internal/service/interfaces/ilocality.go
internal/service/locality.go
internal/service/seller.go

RQ1-LOCALITIES-REPORT-SELLERS

---

internal/handler/locality.go
internal/handler/seller.go
internal/model/locality.go
internal/model/seller.go
internal/repository/interfaces/ilocality.go
internal/repository/locality.go
internal/repository/seller.go
internal/service/interfaces/ilocality.go
internal/service/locality.go
internal/service/seller.go

#112 - Implemented reporting for the carriers repository.

RQ1-LOCALITIES-REPORT-CARRIERS

---

internal/handler/locality.go
internal/handler/seller.go
internal/model/locality.go
internal/model/seller.go
internal/repository/locality.go
internal/repository/seller.go
internal/service/seller.go
pkg/custom_error/locality.go
pkg/custom_error/seller.go

RQ1-INCLUDE-CUSTOM-ERRORS

---

internal/handler/warehouse.go
internal/handler/warehouse_test.go
internal/repository/interfaces/iwarehouse.go
internal/repository/warehouse.go
internal/repository/warehouse_mock.go
internal/service/warehouse.go
internal/service/warehouse_mock.go
internal/service/warehouse_test.go

Este PR implementa um teste unitário para o handler GetAllWarehouse, garantindo que o endpoint /api/v1/warehouses retorna corretamente os dados simulados e o status HTTP 200.

[REQ2] TEST HANDLER WAREHOUSE GET ALL

---

.idea/.gitignore
.idea/alkemy-g7.iml
.idea/vcs.xml
internal/handler/buyer.go
internal/handler/buyer_test.go
internal/handler/purchaseorder.go
internal/handler/purchaseorder_test.go
internal/repository/buyer_mock.go
internal/repository/purchaseorder_mock.go
internal/service/buyer_mock.go
internal/service/buyer_test.go
internal/service/productrec_mock.go
internal/service/purchaseorder.go
internal/service/purchaseorder_mock.go
internal/service/purchaseorder_test.go

Motivação: Cobertura de 100% dos cenarios do Handler e do service das entidades Buyer e Purchase ORder.
Conteúdo da Pull Request:
Adição de testes unitarios do handler e do service do Purchase Order
Complemento de novos cenários do Buyer Handler e Service.
Mudança de nomenclatura(Apenas a primeira letra maiuscula) na struct do service e do Handler

Rq6 sprint2 purcahse order test

---

cmd/dependencies/dependencies.go
internal/repository/interfaces/isection.go
internal/repository/sections_mock.go
internal/service/sections.go
internal/service/sections_test.go

Implementação dos testes para os métodos GET, POST, PATCH e DELETE do service do recurso Section.
|USER STORY ASSOCIADA|BORDA DO CASO|DESCRIÇÃO|
|-|-|-|
|READ|find_all|Se a lista tiver "n" elementos, ele retornará um número do total de elementos.|
|READ|find_by_id_existent|Se o elemento pesquisado pelo id existir, ele retornará as informações do elemento solicitado.|
|READ|find_by_id_non_existent|Se o elemento pesquisado por id não existir, ele retornará null.|
|CREATE|create_ok|Se ele contiver os campos necessários, será criado|
|CREATE|create_conflict|Se o section_number já existir, ele não poderá ser criado.|
|UPDATE| update_existent|Quando a atualização de dados for bem-sucedida, a seção será retornada com as informações atualizadas.|
|UPDATE|update_non_existent|Se a seção a ser …

RQ3 - TEST SERVICE SECTIONS

---

internal/handler/locality.go
internal/handler/locality_test.go
internal/repository/locality.go
internal/repository/locality_test.go
internal/repository/seller_test.go
internal/service/locality_test.go

**This pull request aims to create tests for the entity location in the manipulator layer, in the methods below:**
- Get by ID
- Create locale
- Get carriers
- Get sellers

[RQ1] - LOCALITIE'S HANDLER TESTS

---

cmd/dependencies/dependencies.go
internal/handler/locality.go
internal/handler/locality_test.go
internal/handler/seller.go
internal/handler/seller_test.go
internal/repository/locality.go
internal/repository/seller.go
internal/service/locality.go
internal/service/locality_test.go
internal/service/seller.go
internal/service/seller_test.go

**This pull request aims to include logs in the `seller` and `locality` entities across the handler, repository, and service layers.** 
For this, it was necessary to use:
- database/sql
- log
- time
- github.com/go-sql-driver/mysql
- github.com/sirupsen/logrus

[RQ1] - SELLER LOCALITY LOGGER
